version: '3.8'

services:
  organic-compounds-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: organic-compounds-simulator
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    volumes:
      # Optional: Mount local directory for development
      # - ./:/app
      # Optional: Cache directory for pip packages
      - pip-cache:/root/.cache/pip
    networks:
      - organic-compounds-net
      - proxy-network

networks:
  organic-compounds-net:
    driver: bridge
  proxy-network:
    external: true

volumes:
  pip-cache: