[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "light"
primaryColor = "#7c3aed"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f5"
textColor = "#262730"

[browser]
gatherUsageStats = false